- name: install nginx at a time in multiple servers
  hosts: nginx

  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
      enabled: true

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started    